--[[
    CooldownCompanion - Core/Defaults.lua: Profile schema and override sections registry
]]

local ADDON_NAME, ST = ...

-- Default database structure
local defaults = {
    global = {
        characterInfo = {},  -- [charKey] = { classFilename, classID }
    },
    profile = {
        minimap = {
            hide = false,
        },
        hideInfoButtons = false,
        escClosesConfig = true,
        showAdvanced = {},
        autoAddPrefs = {
            lastSource = "actionbars",
            selectedBars = { true, true, true, true, true, true },
            showSkipped = false,
            showSources = true,
            sortMode = "source_then_name",
        },
        groupSettingPresets = {
            icons = {},
            bars = {},
        },
        groups = {
            --[[
                [groupId] = {
                    name = "Group Name",
                    anchor = {
                        point = "CENTER",
                        relativeTo = "UIParent",
                        relativePoint = "CENTER",
                        x = 0,
                        y = 0,
                    },
                    buttons = {
                        [index] = {
                            type = "spell" or "item",
                            id = spellId or itemId,
                            name = "Spell/Item Name",
                        }
                    },
                    style = {
                        buttonSize = 36,
                        buttonSpacing = 2,
                        borderSize = 1,
                        borderColor = {0, 0, 0, 1},
                        backgroundColor = {0, 0, 0, 0.5},
                        orientation = "horizontal", -- "horizontal" or "vertical"
                        growthOrigin = "TOPLEFT", -- "TOPLEFT", "TOPRIGHT", "BOTTOMLEFT", "BOTTOMRIGHT"
                        buttonsPerRow = 12,
                        showCooldownText = true,
                        cooldownFontSize = 12,
                        cooldownFontOutline = "OUTLINE",
                        cooldownFont = "Friz Quadrata TT",
                        cooldownFontColor = {1, 1, 1, 1},
                        cooldownTextAnchor = "CENTER",
                        cooldownTextXOffset = 0,
                        cooldownTextYOffset = 0,
                        separateTextPositions = false,
                        auraTextAnchor = "TOPLEFT",
                        auraTextXOffset = 2,
                        auraTextYOffset = -2,
                        showAuraText = true, -- nil defaults to true via ~= false
                        auraTextFont = "Friz Quadrata TT",
                        auraTextFontSize = 12,
                        auraTextFontOutline = "OUTLINE",
                        auraTextFontColor = {0, 0.925, 1, 1},
                        iconWidthRatio = 1.0, -- 1.0 = square, <1 = taller, >1 = wider
                        maintainAspectRatio = true, -- Prevent icon image stretching
                        showTooltips = false,
                        desaturateOnCooldown = true, -- Desaturate icon while on cooldown
                        showCooldownSwipe = true,
                        showCooldownSwipeFill = true,
                        cooldownSwipeReverse = false,
                        showCooldownSwipeEdge = true,
                        cooldownSwipeAlpha = 0.8,
                        cooldownSwipeEdgeColor = {1, 1, 1, 1},
                        showGCDSwipe = false, -- Show GCD swipe animation on icons
                        showOutOfRange = true, -- Red-tint icons when target is out of range
                        showAssistedHighlight = false, -- Highlight the assisted combat recommended spell
                        assistedHighlightHostileTargetOnly = true, -- Show only for hostile (attackable) targets
                        assistedHighlightStyle = "blizzard", -- "blizzard", "solid", or "proc"
                        assistedHighlightColor = {0.3, 1, 0.3, 0.9},
                        assistedHighlightBorderSize = 2,
                        assistedHighlightBlizzardOverhang = 32, -- % overhang for blizzard style
                        assistedHighlightProcOverhang = 32, -- % overhang for proc style
                        assistedHighlightProcColor = {1, 1, 1, 1},
                        assistedHighlightCombatOnly = false,
                        showUnusable = true,
                        iconUnusableTintColor = {0.4, 0.4, 0.4, 1},
                        iconTintColor = {1, 1, 1, 1},           -- base icon vertex color (RGBA)
                        iconCooldownTintEnabled = false,         -- apply separate tint when on cooldown
                        iconCooldownTintColor = {1, 0, 0.102, 1}, -- cooldown tint (default: 60% opacity white)
                        iconAuraTintEnabled = false,             -- apply separate tint when aura is active
                        iconAuraTintColor = {0, 0.925, 1, 1},       -- aura tint (default: white full opacity)
                        showLossOfControl = false,
                        procGlowOverhang = 32,
                        procGlowColor = {1, 1, 1, 1},
                        procGlowStyle = "glow",
                        procGlowSize = 30,
                        procGlowThickness = 4,
                        procGlowSpeed = 50,
                        procGlowLines = 8,
                        procGlowCombatOnly = false,
                        pandemicGlowStyle = "solid",
                        pandemicGlowColor = {1, 0.5, 0, 1},
                        pandemicGlowSize = 5,
                        pandemicGlowThickness = 4,
                        pandemicGlowSpeed = 50,
                        pandemicGlowLines = 8,
                        pandemicGlowCombatOnly = false,
                        barPandemicColor = {1, 0.5, 0, 1},
                        pandemicBarEffect = "none",
                        pandemicBarEffectColor = {1, 0.5, 0, 1},
                        pandemicBarEffectSize = 5,
                        pandemicBarEffectThickness = 4,
                        pandemicBarEffectSpeed = 50,
                        pandemicBarEffectLines = 8,
                        auraGlowStyle = "pixel",
                        auraGlowColor = {1, 0.84, 0, 0.9},
                        auraGlowSize = 8,
                        auraGlowThickness = 4,
                        auraGlowSpeed = 50,
                        auraGlowLines = 8,
                        auraGlowInvert = false,
                        auraGlowCombatOnly = false,
                        readyGlowStyle = "none",
                        readyGlowColor = {0.2, 1.0, 0.2, 1},
                        readyGlowSize = 5,
                        readyGlowThickness = 4,
                        readyGlowSpeed = 50,
                        readyGlowLines = 8,
                        readyGlowCombatOnly = false,
                        readyGlowDuration = 0,
                        keyPressHighlightStyle = "none",
                        keyPressHighlightColor = {1, 1, 1, 0.4},
                        keyPressHighlightSize = 5,
                        keyPressHighlightCombatOnly = false,
                        barAuraColor = {0.2, 1.0, 0.2, 1.0},
                        barAuraEffect = "color",
                        barAuraEffectColor = {1, 0.84, 0, 0.9},
                        barAuraEffectSize = 8,
                        barAuraEffectThickness = 4,
                        barAuraEffectSpeed = 50,
                        barAuraEffectLines = 8,
                        strataOrder = nil, -- custom layer order (array of 4 keys) or nil for default
                        showKeybindText = false,
                        keybindFont = "Friz Quadrata TT",
                        keybindFontSize = 10,
                        keybindFontOutline = "OUTLINE",
                        keybindFontColor = {1, 1, 1, 1},
                        keybindAnchor = "TOPRIGHT",
                        keybindXOffset = -2,
                        keybindYOffset = -2,
                        showChargeText = true,
                        chargeFont = "Friz Quadrata TT",
                        chargeFontSize = 12,
                        chargeFontOutline = "OUTLINE",
                        chargeFontColor = {1, 1, 1, 1},
                        chargeFontColorMissing = {1, 1, 1, 1},
                        chargeFontColorZero = {1, 1, 1, 1},
                        chargeAnchor = "BOTTOMRIGHT",
                        chargeXOffset = -2,
                        chargeYOffset = 2,
                    },
                    enabled = true,
                    displayMode = "icons",    -- "icons" or "bars"
                    frameStrata = nil,        -- nil = "MEDIUM" (default), or "BACKGROUND"/"LOW"/"HIGH"/"DIALOG"
                    -- Alpha fade system
                    baselineAlpha = 1,        -- alpha when no force conditions met (0-1)
                    forceAlphaInCombat = false,
                    forceAlphaOutOfCombat = false,
                    forceAlphaRegularMounted = false,
                    forceAlphaDragonriding = false,
                    forceAlphaTargetExists = false,
                    forceAlphaMouseover = false,
                    -- Force-hidden conditions (drive alpha to 0)
                    forceHideInCombat = false,
                    forceHideOutOfCombat = false,
                    forceHideRegularMounted = false,
                    forceHideDragonriding = false,
                    fadeDelay = 1,            -- seconds before fading after mouseover ends
                    fadeInDuration = 0.2,     -- fade-in animation seconds
                    fadeOutDuration = 0.2,    -- fade-out animation seconds
                    -- Load conditions: true = unload group in this context
                    loadConditions = {
                        raid = false,
                        dungeon = false,
                        delve = false,
                        battleground = false,
                        arena = false,
                        openWorld = false,
                        rested = false,
                        petBattle = true,
                        vehicleUI = true,
                    },
                }
            ]]
        },
        nextGroupId = 1,
        groupContainers = {},  -- [containerId] = { name, order, folderId, enabled, locked, specs, heroTalents, loadConditions, alpha/fade, anchor, ... }
        nextContainerId = 1,
        folders = {},       -- [folderId] = { name, order, section, manualIcon?, specs?, heroTalents? }
        nextFolderId = 1,
        globalStyle = {
            buttonSize = 36,
            buttonSpacing = 2,
            borderSize = 1,
            borderColor = {0, 0, 0, 1},
            cooldownFontSize = 12,
            cooldownFontOutline = "OUTLINE",
            cooldownFont = "Friz Quadrata TT",
            cooldownFontColor = {1, 1, 1, 1},
            cooldownTextAnchor = "CENTER",
            cooldownTextXOffset = 0,
            cooldownTextYOffset = 0,
            separateTextPositions = false,
            auraTextAnchor = "TOPLEFT",
            auraTextXOffset = 2,
            auraTextYOffset = -2,
            iconWidthRatio = 1.0,
            maintainAspectRatio = true,
            showTooltips = false,
            desaturateOnCooldown = true,
            showCooldownSwipe = true,
            showCooldownSwipeFill = true,
            cooldownSwipeReverse = false,
            showCooldownSwipeEdge = true,
            cooldownSwipeAlpha = 0.8,
            cooldownSwipeEdgeColor = {1, 1, 1, 1},
            showGCDSwipe = false,
            showOutOfRange = true,
            showAssistedHighlight = false,
            assistedHighlightHostileTargetOnly = true,
            assistedHighlightStyle = "blizzard",
            assistedHighlightColor = {0.3, 1, 0.3, 0.9},
            assistedHighlightBorderSize = 2,
            assistedHighlightBlizzardOverhang = 32,
            assistedHighlightProcOverhang = 32,
            assistedHighlightCombatOnly = false,
            showUnusable = false,
            iconUnusableTintColor = {0.4, 0.4, 0.4, 1},
            iconTintColor = {1, 1, 1, 1},
            iconCooldownTintEnabled = false,
            iconCooldownTintColor = {1, 0, 0.102, 1},
            iconAuraTintEnabled = false,
            iconAuraTintColor = {0, 0.925, 1, 1},
            showLossOfControl = false,
            procGlowOverhang = 32,
            procGlowColor = {1, 1, 1, 1},
            procGlowStyle = "glow",
            procGlowSize = 30,
            procGlowThickness = 4,
            procGlowSpeed = 50,
            procGlowLines = 8,
            procGlowCombatOnly = false,
            pandemicGlowStyle = "solid",
            pandemicGlowColor = {1, 0.5, 0, 1},
            pandemicGlowSize = 5,
            pandemicGlowThickness = 4,
            pandemicGlowSpeed = 50,
            pandemicGlowLines = 8,
            pandemicGlowCombatOnly = false,
            barPandemicColor = {1, 0.5, 0, 1},
            pandemicBarEffect = "none",
            pandemicBarEffectColor = {1, 0.5, 0, 1},
            pandemicBarEffectSize = 5,
            pandemicBarEffectThickness = 4,
            pandemicBarEffectSpeed = 50,
            pandemicBarEffectLines = 8,
            auraGlowStyle = "pixel",
            auraGlowColor = {1, 0.84, 0, 0.9},
            auraGlowSize = 8,
            auraGlowThickness = 4,
            auraGlowSpeed = 50,
            auraGlowLines = 8,
            auraGlowInvert = false,
            auraGlowCombatOnly = false,
            readyGlowStyle = "none",
            readyGlowColor = {0.2, 1.0, 0.2, 1},
            readyGlowSize = 5,
            readyGlowThickness = 4,
            readyGlowSpeed = 50,
            readyGlowLines = 8,
            readyGlowCombatOnly = false,
            readyGlowDuration = 0,
            keyPressHighlightStyle = "none",
            keyPressHighlightColor = {1, 1, 1, 0.4},
            keyPressHighlightSize = 5,
            keyPressHighlightCombatOnly = false,
            barAuraColor = {0.2, 1.0, 0.2, 1.0},
            barAuraEffect = "color",
            barAuraEffectColor = {1, 0.84, 0, 0.9},
            barAuraEffectSize = 8,
            barAuraEffectThickness = 4,
            barAuraEffectSpeed = 50,
            barAuraEffectLines = 8,
            assistedHighlightProcColor = {1, 1, 1, 1},
            strataOrder = nil,
            showKeybindText = false,
            keybindFont = "Friz Quadrata TT",
            keybindFontSize = 10,
            keybindFontOutline = "OUTLINE",
            keybindFontColor = {1, 1, 1, 1},
            keybindAnchor = "TOPRIGHT",
            keybindXOffset = -2,
            keybindYOffset = -2,
            showChargeText = true,
            chargeFont = "Friz Quadrata TT",
            chargeFontSize = 12,
            chargeFontOutline = "OUTLINE",
            chargeFontColor = {1, 1, 1, 1},
            chargeFontColorMissing = {1, 1, 1, 1},
            chargeFontColorZero = {1, 1, 1, 1},
            chargeAnchor = "BOTTOMRIGHT",
            chargeXOffset = -2,
            chargeYOffset = 2,
            -- Bar display mode defaults
            barLength = 180,
            barHeight = 20,
            barColor = {0.2, 0.6, 1.0, 1.0},
            barCooldownColor = {0.6, 0.13, 0.18, 1.0},
            barChargeColor = {1.0, 0.82, 0.0, 1.0},
            barBgColor = {0.1, 0.1, 0.1, 0.8},
            showBarIcon = true,
            barIconSizeOverride = false,
            barIconSize = 20,
            showBarNameText = true,
            barNameFont = "Friz Quadrata TT",
            barNameFontSize = 10,
            barNameFontOutline = "OUTLINE",
            barNameFontColor = {1, 1, 1, 1},
            showBarReadyText = false,
            barReadyText = "Ready",
            barReadyTextColor = {0.2, 1.0, 0.2, 1.0},
            barReadyFontSize = 12,
            barReadyFont = "Friz Quadrata TT",
            barReadyFontOutline = "OUTLINE",
            barUpdateInterval = 0.025,  -- seconds between bar fill updates (~40Hz default)
            barTexture = "Solid",
            -- Text display mode defaults
            textWidth = 200,
            textHeight = 20,
            textFormat = "{name}  {status}",
            textFont = "Friz Quadrata TT",
            textFontSize = 12,
            textFontOutline = "OUTLINE",
            textFontColor = {1, 1, 1, 1},
            textAlignment = "LEFT",
            textCooldownColor = {1, 0.3, 0.3, 1},
            textReadyColor = {0.2, 1.0, 0.2, 1},
            textReadyText = "Ready",
            textAuraColor = {0, 0.925, 1, 1},
            textCustomColor = {1, 0.82, 0, 1},
            textBgColor = {0, 0, 0, 0},
            textBorderSize = 0,
            textBorderColor = {0, 0, 0, 1},
            textShadow = false,
            decimalTimers = false,
            showTextGroupHeader = false,
            textHeaderFontSize = 12,
            textHeaderFontColor = {1, 1, 1, 1},
        },
        locked = false,
        cdmHidden = false,
        resourceBars = {
            enabled = false,
            anchorGroupId = nil,
            inheritAlpha = false,
            orientation = "horizontal",
            yOffset = 3,
            verticalXOffset = 3,
            barHeight = 12,
            barWidth = 12,
            barSpacing = 3.6,
            verticalFillDirection = "bottom_to_top", -- "bottom_to_top" or "top_to_bottom"
            barTexture = "Solid",
            backgroundColor = { 0, 0, 0, 0.5 },
            borderStyle = "pixel",
            borderColor = { 0, 0, 0, 1 },
            borderSize = 1,
            segmentGap = 4,
            hideManaForNonHealer = true,
            resources = {
                [100] = {
                    enabled = true,
                    mwBaseColor = nil,
                    mwOverlayColor = nil,
                    mwMaxColor = nil,
                    segThresholdEnabled = false,
                    segThresholdValue = 1,
                    segThresholdColor = nil,
                    continuousTickEnabled = false,
                    continuousTickMode = "percent",
                    continuousTickPercent = 50,
                    continuousTickAbsolute = 50,
                    continuousTickColor = nil,
                    continuousTickCombatOnly = false,
                },
                [101] = {
                    enabled = true,
                    staggerGreenColor = nil,
                    staggerYellowColor = nil,
                    staggerRedColor = nil,
                    showText = false,
                    textFormat = "percent",
                },
            },
            customAuraBarSlots = {
                [1] = { position = "below", order = 1001 },
                [2] = { position = "below", order = 1002 },
                [3] = { position = "below", order = 1003 },
                [4] = { position = "below", order = 1004 },
                [5] = { position = "below", order = 1005 },
            },
            customAuraBars = {},
            layoutOrder = {},
            textFont = "Friz Quadrata TT",
            textFontSize = 10,
            textFontOutline = "OUTLINE",
            textFontColor = { 1, 1, 1, 1 },
            textFormat = "current",
            independentAnchorEnabled = false,
            independentAnchorLocked = true,
            independentAnchor = nil,
            independentWidth = nil,
            baselineAlpha = 1,
            forceAlphaInCombat = false,
            forceAlphaOutOfCombat = false,
            forceAlphaRegularMounted = false,
            forceAlphaDragonriding = false,
            forceAlphaTargetExists = false,
            forceAlphaMouseover = false,
            forceHideInCombat = false,
            forceHideOutOfCombat = false,
            forceHideRegularMounted = false,
            forceHideDragonriding = false,
            treatTravelFormAsMounted = false,
            customFade = false,
            fadeDelay = 1,
            fadeInDuration = 0.2,
            fadeOutDuration = 0.2,
        },
        castBar = {
            enabled = false,
            stylingEnabled = true,
            anchorGroupId = nil,
            position = "below",
            order = 2000,
            yOffset = 0,
            height = 15,
            barColor = { 1.0, 0.7, 0.0, 1.0 },
            backgroundColor = { 0, 0, 0, 0.5 },
            barTexture = "Solid",
            showIcon = true,
            iconSize = 16,
            iconFlipSide = false,
            iconOffset = false,
            iconOffsetX = 0,
            iconOffsetY = 0,
            iconBorderSize = 1,
            showSpark = true,
            showSparkTrail = true,
            showInterruptShake = true,
            showInterruptGlow = true,
            showCastFinishFX = true,
            borderStyle = "pixel",
            borderColor = { 0, 0, 0, 1 },
            borderSize = 1,
            showNameText = true,
            nameFont = "Friz Quadrata TT",
            nameFontSize = 10,
            nameFontOutline = "OUTLINE",
            nameFontColor = { 1, 1, 1, 1 },
            showCastTimeText = true,
            castTimeFont = "Friz Quadrata TT",
            castTimeFontSize = 10,
            castTimeFontOutline = "OUTLINE",
            castTimeFontColor = { 1, 1, 1, 1 },
            castTimeXOffset = 0,
            castTimeYOffset = 0,
            independentAnchorEnabled = false,
            independentAnchorLocked = true,
            independentAnchor = nil,
            independentWidth = nil,
        },
        frameAnchoring = {
            enabled = false,
            anchorGroupId = nil,
            mirroring = true,
            inheritAlpha = true,
            unitFrameAddon = nil,
            customPlayerFrame = "",
            customTargetFrame = "",
            player = {
                anchorPoint = "RIGHT",
                relativePoint = "LEFT",
                xOffset = -10,
                yOffset = 0,
            },
            target = {
                anchorPoint = "LEFT",
                relativePoint = "RIGHT",
                xOffset = 10,
                yOffset = 0,
            },
        },
    },
}

ST._defaults = defaults

------------------------------------------------------------------------
-- OVERRIDE SECTIONS REGISTRY
-- Maps section IDs to their labels, style keys, and applicable display modes.
-- Used by promote/revert logic and UI builders.
------------------------------------------------------------------------
ST.OVERRIDE_SECTIONS = {
    -- Icon Mode — Appearance Tab
    borderSettings = {
        label = "Border",
        keys = {"borderSize", "borderColor"},
        modes = {icons = true, bars = true},
    },
    cooldownText = {
        label = "Cooldown Text",
        keys = {"showCooldownText", "decimalTimers", "cooldownFont", "cooldownFontSize", "cooldownFontOutline", "cooldownFontColor", "cooldownTextAnchor", "cooldownTextXOffset", "cooldownTextYOffset"},
        modes = {icons = true, bars = true},
    },
    auraText = {
        label = "Aura Duration Text",
        keys = {"showAuraText", "auraTextFont", "auraTextFontSize", "auraTextFontOutline", "auraTextFontColor", "separateTextPositions", "auraTextAnchor", "auraTextXOffset", "auraTextYOffset"},
        modes = {icons = true, bars = true},
    },
    auraStackText = {
        label = "Aura Stack Text",
        keys = {"showAuraStackText", "auraStackFont", "auraStackFontSize", "auraStackFontOutline", "auraStackFontColor", "auraStackAnchor", "auraStackXOffset", "auraStackYOffset"},
        modes = {icons = true, bars = true},
    },
    keybindText = {
        label = "Keybind Text",
        keys = {"showKeybindText", "keybindFont", "keybindFontSize", "keybindFontOutline", "keybindFontColor", "keybindAnchor", "keybindXOffset", "keybindYOffset"},
        modes = {icons = true},
    },
    chargeText = {
        label = "Charge Text",
        keys = {"showChargeText", "chargeFont", "chargeFontSize", "chargeFontOutline", "chargeFontColor", "chargeFontColorMissing", "chargeFontColorZero", "chargeAnchor", "chargeXOffset", "chargeYOffset"},
        modes = {icons = true, bars = true},
    },
    -- Icon Mode — Extras Tab
    desaturation = {
        label = "Desaturation",
        keys = {"desaturateOnCooldown"},
        modes = {icons = true, bars = true},
    },
    cooldownSwipe = {
        label = "Cooldown Swipe",
        keys = {"showCooldownSwipe", "showCooldownSwipeFill", "cooldownSwipeReverse", "showCooldownSwipeEdge", "cooldownSwipeAlpha", "cooldownSwipeEdgeColor"},
        modes = {icons = true},
    },
    showGCDSwipe = {
        label = "Show GCD Swipe",
        keys = {"showGCDSwipe"},
        modes = {icons = true, bars = true},
    },
    showOutOfRange = {
        label = "Show Out of Range",
        keys = {"showOutOfRange"},
        modes = {icons = true},
    },
    showTooltips = {
        label = "Show Tooltips",
        keys = {"showTooltips"},
        modes = {icons = true, bars = true},
    },
    lossOfControl = {
        label = "Loss of Control",
        keys = {"showLossOfControl"},
        modes = {icons = true, bars = true},
    },
    unusableDimming = {
        label = "Unusable Dimming",
        keys = {"showUnusable", "iconUnusableTintColor"},
        modes = {icons = true, bars = true},
    },
    iconTint = {
        label = "Icon Tint",
        keys = {"iconTintColor", "iconCooldownTintEnabled", "iconCooldownTintColor", "iconAuraTintEnabled", "iconAuraTintColor", "backgroundColor"},
        modes = {icons = true, bars = true},
    },
    assistedHighlight = {
        label = "Assisted Highlight",
        keys = {"showAssistedHighlight", "assistedHighlightHostileTargetOnly", "assistedHighlightStyle", "assistedHighlightColor", "assistedHighlightBorderSize", "assistedHighlightBlizzardOverhang", "assistedHighlightProcOverhang", "assistedHighlightProcColor", "assistedHighlightCombatOnly"},
        modes = {icons = true},
    },
    procGlow = {
        label = "Proc Glow",
        keys = {"procGlowStyle", "procGlowColor", "procGlowSize", "procGlowThickness", "procGlowSpeed", "procGlowLines", "procGlowCombatOnly"},
        modes = {icons = true},
    },
    pandemicGlow = {
        label = "Pandemic Glow",
        keys = {"showPandemicGlow", "pandemicGlowStyle", "pandemicGlowColor", "pandemicGlowSize", "pandemicGlowThickness", "pandemicGlowSpeed", "pandemicGlowLines", "pandemicGlowCombatOnly"},
        modes = {icons = true},
    },
    auraIndicator = {
        label = "Show Aura Glow",
        keys = {"auraGlowStyle", "auraGlowColor", "auraGlowSize", "auraGlowThickness", "auraGlowSpeed", "auraGlowLines", "auraGlowInvert", "auraGlowCombatOnly"},
        modes = {icons = true},
    },
    readyGlow = {
        label = "Ready Glow",
        keys = {"readyGlowStyle", "readyGlowColor", "readyGlowSize", "readyGlowThickness", "readyGlowSpeed", "readyGlowLines", "readyGlowCombatOnly", "readyGlowDuration"},
        modes = {icons = true},
    },
    keyPressHighlight = {
        label = "Key Press Highlight",
        keys = {"keyPressHighlightStyle", "keyPressHighlightColor", "keyPressHighlightSize", "keyPressHighlightCombatOnly"},
        modes = {icons = true},
    },
    -- Bar Mode — Appearance Tab
    pandemicBar = {
        label = "Pandemic Indicator",
        keys = {"showPandemicGlow", "barPandemicColor", "pandemicBarEffect", "pandemicBarEffectColor", "pandemicBarEffectSize", "pandemicBarEffectThickness", "pandemicBarEffectSpeed", "pandemicBarEffectLines", "pandemicGlowCombatOnly"},
        modes = {bars = true},
    },
    barActiveAura = {
        label = "Active Aura Indicator",
        keys = {"barAuraColor", "barAuraEffect", "barAuraEffectColor", "barAuraEffectSize", "barAuraEffectThickness", "barAuraEffectSpeed", "barAuraEffectLines", "auraGlowCombatOnly"},
        modes = {bars = true},
    },
    barIcon = {
        label = "Bar Icon",
        keys = {"showBarIcon", "barIconReverse", "barIconOffset", "barIconSizeOverride", "barIconSize"},
        modes = {bars = true},
    },
    barColors = {
        label = "Bar Colors",
        keys = {"barColor", "barCooldownColor", "barChargeColor", "barBgColor"},
        modes = {bars = true},
    },
    barNameText = {
        label = "Name Text",
        keys = {"showBarNameText", "barNameTextReverse", "barNameFont", "barNameFontSize", "barNameFontOutline", "barNameFontColor"},
        modes = {bars = true},
    },
    barReadyText = {
        label = "Ready Text",
        keys = {"showBarReadyText", "barReadyText", "barReadyTextColor", "barReadyFontSize", "barReadyFont", "barReadyFontOutline"},
        modes = {bars = true},
    },
    -- Text Mode
    textDimensions = {
        label = "Text Dimensions",
        keys = {"textWidth", "textHeight", "showTextGroupHeader", "textHeaderFontSize", "textHeaderFontColor"},
        modes = {text = true},
    },
    textFormat = {
        label = "Format String",
        keys = {"textFormat"},
        modes = {text = true},
    },
    textFont = {
        label = "Text Font",
        keys = {"textFont", "textFontSize", "textFontOutline", "textAlignment", "textShadow"},
        modes = {text = true},
    },
    textColors = {
        label = "Text Colors",
        keys = {"textFontColor", "textCooldownColor", "textReadyColor", "textAuraColor", "textCustomColor", "textReadyText"},
        modes = {text = true},
    },
    textBackground = {
        label = "Text Background",
        keys = {"textBgColor", "textBorderSize", "textBorderColor"},
        modes = {text = true},
    },
}
